### ISSUE TITLE
Unfocused workspace on another screen doesn't refresh

### ISSUE THREAD

**Issue by asiantuntija** [swaywm/wlroots#2216]
Rightmost screen stops refreshing content immediately when losing focus as a result of keybind being pressed. On the contrary, moving cursor to next screen, it keeps updating normally until cursor gets over a border of a window, or enters for example this form in the browser.

When updating stops:
[ERROR] [backend/drm/atomic.c:36] DP-1: Atomic commit failed (pageflip): Invalid argument

Over a border on other screen:
[sway/input/cursor.c:835] denying request to set cursor from unfocused client

Workspace being focused (probably not related):
[ERROR] [backend/drm/atomic.c:177] setting gamma LUT 4096

Output setting from my config:
### Output configuration
    output HDMI-A-1 resolution 3840x2160@60Hz position 0,0 disable
    output DP-3 resolution 3840x2160 position 3840,0
    output DP-1 resolution 2560x1440 position 7680,0 adaptive_sync on max_render_time 1
    output * bg #000000 solid_color

Tried also disabling adaptive_sync, no effect.

Latest wlroots and sway.

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

Can you obtain DRM debug logs? See https://github.com/swaywm/wlroots/wiki/DRM-Debugging

**Comment by asiantuntija** [comment]
[dmesg.log](https://github.com/swaywm/wlroots/files/4661072/dmesg.log)
[sway.log](https://github.com/swaywm/wlroots/files/4661074/sway.log)

**Comment by emersion** [comment]
```
[   30.801050] [drm:dm_update_plane_state [amdgpu]] Bad cursor position -897, 1256
[   30.801138] [drm:amdgpu_dm_atomic_check [amdgpu]] Atomic check failed with err: -22 
[   30.801148] [drm:drm_atomic_check_only [drm]] atomic driver check for 000000007cf7105d failed: -22
```

**Comment by David96** [comment]
I can confirm this issue, I noticed that the freeze happens whenever I hover something that changes the cursor (I think that's also what happens when you move your mouse over a border).

**Comment by asiantuntija** [comment]
Managed to narrow it down a bit:
fa5d709fc3ea96b14163cdad435caccdbdd5bbda still working
8da9d9679e4cad640b0f0a518ca1529c8cdecbe0 doesn't compile
be90062c51ba5470f513aa118d99472c304e8f36 doesn't compile
52281cb8ba7e0badd92662ade136d25929a67828 not working

**Comment by emersion** [comment]
Should be fixed by https://lists.freedesktop.org/archives/amd-gfx/2020-May/049825.html

**Comment by progandy** [comment]
Maybe ```drm_connector_move_cursor``` should toggle ```cursor_enabled``` when it is out of bounds? It is not very useful to commit an invisible cursor plane.

**Comment by emersion** [comment]
Yup, that would be a good idea. However I thought we already had that logic in `wlr_output` directly (see the "visible" field).

**Comment by progandy** [comment]
I don't think that "visible" field is propagated to the hardware cursor. ```cursor_enabled``` is only set to false when setting the cursor texture fails. Commit 52281cb always tries to render the cursor if that field is true.

**Comment by David96** [comment]
> Should be fixed by https://lists.freedesktop.org/archives/amd-gfx/2020-May/049825.html

That does fix the issue, but slightly off topic: is there a simpler way to test this kind of patch than building the whole kernel? I tried doing only ```make M=drivers/gpu/drm``` and then using the newly built amdgpu module but for some reason that didn't include your patch (still the same issue with the same "Bad cursor position" log which obviously wouldn't be possible when running the patched version).

**Comment by ppascher** [comment]
starting sway with WLR_NO_HARDWARE_CURSORS=1 fixes this as a quick solution until we get the amdgpu patch (as the hardware cursor seems not to receive the "visible" field as @progandy mentioned).

**Comment by emersion** [comment]
>I don't think that "visible" field is propagated to the hardware cursor. 

Ah, indeed, `visible` is only used for enter/leave events.

Using `cursor_enabled` might not be straightforward, since we don't want to show a previous cursor when an out-of-bounds disabled cursor becomes in-bounds again.

**Comment by progandy** [comment]
I haven't tested it, but to me it seems possible that a similar error could also occur if you modeset a smaller resolution and the cursor is then out of bounds?

**Comment by emersion** [comment]
>modeset a smaller resolution and the cursor is then out of bounds

No, the EINVAL check in amdgpu is only about negative coords.

**Comment by emersion** [comment]
amdgpu patch has been merged.
