### ISSUE TITLE
[RFC] Proposal: Allow compositors to setup EGL manually

### ISSUE THREAD

**Issue by ammen99** [swaywm/wlroots#987]
Currently the backend creates EGL itself. However, this doesn't let compositors specify EGL context attributes and perhaps some other options. While I certainly don't have much experience or knowledge of wlroots' backend code, I think something like the following can be implemented:

1) `wlr_backend_autocreate()` and similar are used to initialize the backend, but NOT the renderer.
2) Implement a new function, called for example `wlr_backend_attempt_egl(backend, attribs, ...)` in order to create the EGL context. This function can also create the GLES or whatever renderer, or perhaps this can be yet another function which must be called manually.

In this way we can not only support the different attribs of EGL, but also choose which renderer to create. For example when we have a vulkan renderer in the future, the compositor will be able to choose whether to use it or the "old" GL renderer.

**Comment by emersion** [comment]
I'm not a fan of this idea because
1. This would require one custom function per renderer
2. This would make it impossible to write custom renderers

I think this issue should be fixed with a custom GLES2 renderer (reusing as much as wlroot's GLES2 renderer as possible). This would give more flexibility and more freedom to wlroots users, as every aspect of the renderer would be customizable. In this case the question becomes: how do I tell the backend to use my custom GLES2 renderer instead of creating a new one?

Related: #774

**Comment by ammen99** [comment]
In this case the compositor must have access to the backend internals(AFAIK egl initialization requires gbm in drm backend, remote display in wayland backend)? Or maybe we should still provide `backend_attempt_egl()` without changing the current behaviour when creating a backend?

About reusing GL renderer and implementing custom renderers: I think it might be possible, but tricky if we have more than one EGL context. Eventually there will be something like the wlr_multi_renderer/texture you proposed some time ago, as we have to share textures between renderers if they are to live side by side. Or we just let the compositor change the EGL context of the backend renderer(assuming the renderer is EGL/GLES) so that both the custom renderer and the built-in one operate in the same context and interoperability is much easier.

Sorry if the above isn't what you had in mind, but that's what I could think of.

**Comment by emersion** [comment]
>In this case the compositor must have access to the backend internals(AFAIK egl initialization requires gbm in drm backend, remote display in wayland backend)?

See the other issue, in particular [this comment](https://github.com/swaywm/wlroots/issues/774#issuecomment-380853507). Since this is a really big redesign, we migth want an intermediate solution to let users customize the renderer without drastically changing the API. A possible intermediate solution would be to give to the backend the callback that creates the renderer:

```c
typedef struct wlr_renderer *(*wlr_renderer_create_func_t)(EGLenum platform,
	void *remote_display, EGLint *config_attribs, EGLint visual_id);
struct wlr_backend *wlr_backend_autocreate(struct wl_display *display,
	wlr_renderer_create_func_t create_backend_func);
```

This requires renderers to be backed by EGL for now (which is required anyway because hardcoded in all backends). If needed, we can add back `wlr_renderer_get_egl` so that the backend can access `wlr_egl` directly.

> I think it might be possible, but tricky if we have more than one EGL context.

Multiple renderers at the same time are not happening sadly.

> Sorry if the above isn't what you had in mind, but that's what I could think of.

Really, I didn't have "something in mind" before starting this discussion. I'm exploring ideas and trying to find the best solution, just like you.

**Comment by ascent12** [comment]
@ammen99 
>Sorry if the above isn't what you had in mind, but that's what I could think of.

In the long term, I want to completely want to remove the dependence on EGL, to open up the possibility of a Vulkan render. It's still not a "solved problem" at this point, and we're really just at the stage of throwing ideas around. Any ideas and feedback on existing ideas are welcome.

There are currently some expected things on the horizon which may shake up how the DRM backend handles its allocations and can interact with EGL/Vulkan, so I'm hesitant to make any changes until more is known, especially since all of this is going to involve massive API breakages.

@emersion
>>I think it might be possible, but tricky if we have more than one EGL context.

>Multiple renderers at the same time are not happening sadly.

It's possible to have multiple opengl contexts associated with an EGLDisplay (with shared data), so that can be multiple "renderers", but doesn't allow us to mix EGLDisplays together.

**Comment by ammen99** [comment]
@emersion 
What you proposed(as a temporary solution) would work perfectly for my purposes. I guess I could live with a patched wlroots until 2.0, but I'd like to be able to use the upstream wlroots.

**Comment by ascent12** [comment]
I'm not against more immediate solutions to allow for users to make their own renderers more easily.

Multiple EGLContexts is something we probably should look more into. The third argument of [eglCreateContext](https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglCreateContext.xhtml) talks about shared data and https://www.khronos.org/opengl/wiki/OpenGL_Object#Object_Sharing has some information about what is shareable.

Maybe it's possible that we leave most of the backend stuff the same, and a user can just leverage a shared context (possibly with [EGL_KHR_create_context](https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_create_context.txt)) to render whatever they want into a normal GL texture, which can be given to wlr_renderer for the final draw. They should be able to extract the GL textures from wlr_textures for their own use as well. Maybe a renderbuffer could be used to make the final draw unnecessary too?

That's is all assuming my understanding of how this works is actually correct, though.

**Comment by ammen99** [comment]
@ascent12

> Maybe a renderbuffer could be used to make the final draw unnecessary too?

As we already make this EGL-specific why not just export the EGLSurface? Then the custom context can  use `eglMakeCurrent()` and render directly to it. But we can't mix both renderers(different contexts can't share glsl programs). While that's not an issue for me if I can have direct access to the GLES name of a `wlr_texture`, it might be desirable for others.

Otherwise AFAIK we can't use renderbuffers to achieve a really efficient rendering, because the custom renderer has to render to the renderbuffer, and this renderbuffer can't be the default FB. (But of course I'm no specialist, maybe there is a way)

> allow for users to make their own renderers more easily

If we go for the workaround that @emersion proposed, we have just one more "change" - just tell the user that the `wlr_renderer_*()` operate in the currently bound framebuffer. In this way they become just functions that the compositor can use for simple rendering operations. Actually that's how I use them currently - to render `wlr_textures` to the appropriate FBs and create my own programs for the "special" effects. In this case I'd also be happy if I had direct access to the GLES name of the `wlr_texture`, but it's optional.

**Comment by ammen99** [comment]
Adding depth and potentially stencil buffer support.

**Comment by ascent12** [comment]
Would just giving the user control of `egl_get_config` be enough, or even just allow them to add a few extra attributes?
That's the place where the size (or presence) of the auxiliary buffers are specified.

**Comment by ammen99** [comment]
> Would just giving the user control of egl_get_config be enough, or even just allow them to add a few extra attributes?

For me even the ability to add a few attributes(namely request alpha, depth and stencil support) is enough. It depends on how generic you guys want the solution to be (even if it is an temporary solution for wlroots 1.0)

> Sure, but how would you do that? wlr_egl is created by the backend, and is private to the backend. Also this still doesn't allow custom renderers.

I thought truly custom renderers were for 2.0?

**Comment by emersion** [comment]
>I thought truly custom renderers were for 2.0?

Non-EGL renders are for v2, but wlroots is not that far from allowing custom EGL renderers (in fact, my solution allows that).

**Comment by emersion** [comment]
>This one?

Yes.

> but the wayland backend seems to call wlr_egl_bind_display(&backend->egl, backend->local_display); between wlr_egl_init() and wlr_gles2_renderer_create()

This is unrelated and should not be done in the backend, but in the renderer. My multi-renderer PR fixed that, but has been closed for unrelated reasons.

>the backends use backend->egl, so a single function to create a renderer and egl at the same time won't work or at least I don't know how to implement.

The point of the proposal is to remove this EGL struct from the backends and let the callback function create it with the renderer, to allow the user to customize all of this.

**Comment by ammen99** [comment]
> The point of the proposal is to remove this EGL struct from the backends and let the callback function create it with the renderer, to allow the user to customize all of this.

Thank you for clarifying this. So the final intention is to tie EGL stuff to the renderer itself, not to the backend? If yes, it seems a logical choice.

**Comment by emersion** [comment]
>So the final intention is to tie EGL stuff to the renderer itself, not to the backend?

Yes. If this change is too big, we could always keep `wlr_egl` in the backend and change the callback to be:

```c
typedef struct wlr_renderer *(*wlr_renderer_create_func_t)(struct wlr_egl *egl, EGLenum platform,
	void *remote_display, EGLint *config_attribs, EGLint visual_id);
```

The callback would call `wlr_egl_init` on `egl`.
